### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by EduSantosBrito** [IsmaelPereira/site-dentista#1]
- [ ] Delimitar funcionalidades a desenvolver

--- 
### Homepage
- [ ] Resolver bug width + de 100%
- [ ] Alinhar menu
- [ ] Tirar outline button
- [ ] Melhorar espaçamento dos elementos na seção About
- [ ] Alinhar textos na seção Tratamentos
- [ ] Arrumar button na seção Tratamentos
- [ ] Alinhar elementos na seção Localização
- [ ] Arrumar texto na seção Localização
- [ ] Aumentar tamanho do mapa na seção Localização
- [ ] Arrumar formulário
- [ ] Resolver bug na seção Footer
- [ ] Alinhar elementos na seção Footer
- [ ] Criar um componente pai para agrupar os componentes: About, Treatment, Local e Contact
- [ ] Criar Router para linkar a segunda página
- [ ] Criar funcionalidade SMTP para contato

### Treatment
- [ ] Fazer a tela toda
